apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://charts.jetstack.io
    name: jetstack/cert-manager
    version: v0.14.3
  values: {}
